### ISSUE TITLE
Error in sparkws.sh "(...)[[: not found"

### ISSUE THREAD

**Issue by lrodero** [47deg/spark-workshop#4]
When running the `sparkws.sh` script, some messages like `(...)/sbin/../bin/load-spark-env.sh: [[: not found` are shown in the console. I'm using Ubuntu 15.04, I don't know if the same errors are shown in other systems.

I think the reason is explained [here](http://unix.stackexchange.com/questions/155838/shell-script-throws-a-not-found-error-when-run-from-a-sh-file-but-if-entered-ma):  _"When bash is run using the name sh, it disables most of its extensions, such as the [[ testing operator."_

**Proposed solution**: Just edit the `sparkws.sh` script and remove the call to `sh` in lines 4,5,8,10 and 13. So for example in line 4 we would change `sh $SPARK_HOME/sbin/stop-master.sh` to `$SPARK_HOME/sbin/stop-master.sh`.

**Comment by juanpedromoreno** [comment]
Thanks @lrodero !

We have just fixed the issue with your proposal and it's working on Mac osx as well, hope it works now on Ubuntu 15.04.

**Comment by lrodero** [comment]
I've just `git pull` the new version, checked it, and it works like a charm :+1:

**Comment by juanpedromoreno** [comment]
:+1: Thanks!
